[workspace]
members = ["derive"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
bb_derive = { path = "derive" }

[package]
name = "bb-machine"
version.workspace = true
edition.workspace = true

[dependencies]
bb_derive.workspace = true
